version: '3'
services:
  web:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./index.html:/var/www/html/index.html
      - ./css:/var/www/html/css
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
